version: "3"

volumes:
  oracle:
networks:
  backend-network:
    driver: bridge

services:

  backend:
    platform: linux/x86_64 #m1 mac 전용 설정
    container_name: backend
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - oracle
    networks:
      - backend-network