version: "3"

volumes:
  mysql-volume:

services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    image: react-nginx-frontend
    ports:
      - "80:80"
    container_name: nginx
    restart: on-failure
    volumes:
      - /client/node_modules
      - ./frontend:/client
    depends_on:
      - spring-boot

  spring-boot:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    image: spring-backend
    ports:
      - "8080:8080"
      - "5005:5005"
    container_name: spring-boot
    restart: on-failure
    depends_on:
      - redis
      - mysql
      - image-analysis

  redis:
    container_name: redis
    image: arm64v8/redis:6.2-alpine
    ports:
      - "6379:6379"

  mysql:
    container_name: mysql
    image: arm64v8/mysql:8.0.30
    env_file:
      - ./backend/.env
    environment:
      - CHARACTER_SET_SERVER=utf8%
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - mysql-volume:/var/lib/${MYSQL_DATABASE}
    ports:
      - "3306:3306"

  image-analysis:
    build:
      context: ./imageAnalysis
      dockerfile: Dockerfile
    image: image-analysis
    container_name: image-analysis
    command: gunicorn --bind 0.0.0.0:5001 app:app
    ports:
      - "5001:5001"
    volumes:
      - ./imageAnalysis/:/app

  #grafana
  #prometheus
  #cadvisor
  #nodexporter