version: '3'
#TODO: NOT complete
services:
  backend:
    platform: linux/x86_64 #m1 mac 전용 설정
    container_name: backend
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
    links:
      - oracle
    depends_on:
      - oracle
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@localhost:1521/xe
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - backend-network