version: "3"

services:
#  react-btb:
#    image: node:16-alpine
#    command: sh -c "npm install && npm start"
#    ports:
#      - "3000:3000"
#    working_dir: /app
#    volumes:
#      - ./frontend:/app
#    container_name: react-btb

  spring-boot-btb:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: spring-backend
    ports:
      - "8080:8080"
      - "5005:5005"
    container_name: spring-boot-btb
#     restart: always
    depends_on:
      - redis-btb

  redis-btb:
    container_name: redis-btb
    image: arm64v8/redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisBtb

volumes:
#  mysqlBtb:
  redisBtb:

  #grafana
  #prometheus
  #cadvisor
  #nodexporter