spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/btb-db?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    url: jdbc:mysql://mysql:3306/btb-db?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
#    url: jdbc:mysql://${DB_URL}//btb-db?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul

    database: btb-db
    username: "root"
    password: "btbdatabase"
#    username: ${DB_USERNAME}
#    password: ${MYSQL_ROOT_PASSWORD}

#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:

  jpa:
    database: "mysql"
    show-sql: "true"
    hibernate:
      ddl-auto: "validate"
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true