cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: error
    com.amazonaws.internal.InstanceMetadataServiceResourceFetcher: error