spring:
  profiles:
    include:
      - database
      - cache
      - aws
      - credentials
      - imageAnalysis
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

pythonServer:
  address: http://image-analysis:5001
  url: /api-python/compare