spring:
  profiles:
    include:
      - database
      - cache
      - aws
      - credentials
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

pythonServer:
#  address: http://localhost:5001
  address: http://image-analysis:5001
  url: /api-python/v1/compare